version: "3"
services:
  client:
    image: client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - employee-management-app
  server:
    image: server
    ports:
      - "5001:5001"
    networks:
      - employee-management-app
    depends_on:
      - postgres
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
networks:
  employee-management-app:
    driver: bridge
volumes:
  postgres-data:
    driver: local
