version: "3"
services:
  client:
    image: client
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - API_SERVER_URL=http://localhost:5000
    networks:
      - employee-management-app
  server:
    image: server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=local
      - PORT=5000
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    networks:
      - employee-management-app
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  employee-management-app:
    driver: bridge
volumes:
  postgres-data:
    driver: local
